spring.application.name=invoiceService
server.port=9003
spring.datasource.url=jdbc:mysql://localhost:3306/vconf
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

jwt.secret=MySecretKeyForJwt123456789012345

# Email configuration
mail.username=tsamruddhi16@gmail.com
mail.password=hqixsjpptyvizhae

# File storage path (already using this)
# File storage path (External path as requested)
file.path=C:/vconf/files